{% set name = "colorclass" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6d4fe287766166a98ca7bc6f6312daf04a0481b1eda43e7173484051c0ab4366

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >= 2.6
    - pip
    - poetry >=0.12
  run:
    - python >=2.6

test:
  imports:
    - colorclass

about:
  home: https://github.com/matthewdeanmartin/colorclass
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Colorful worry-free console applications for Linux, Mac OS X, and Windows.
  description: |
    Yet another ANSI color text library for Python. Provides “auto colors” for
    dark/light terminals. Works on Linux, OS X, and Windows. For Windows support
    you just need to call `Windows.enable()` in your application.
  dev_url: https://github.com/matthewdeanmartin/colorclass

extra:
  recipe-maintainers:
    - carlodri
